name: SQL Lint and dbt Tests

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-dbt:
    runs-on: ubuntu-latest

    env:
      DBT_HOST: ep-frosty-math-anosahcy-pooler.c-6.us-east-1.aws.neon.tech
      DBT_USER: neondb_owner
      DBT_PASSWORD: npg_g5hVQRvYS6uk
      DBT_PORT: 5432
      DBT_DBNAME: neondb
      DBT_SCHEMA: public

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff sqlfluff-templater-dbt dbt-postgres

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          fintech_analytics:
            target: dev
            outputs:
              dev:
                type: postgres
                host: ${DBT_HOST}
                user: ${DBT_USER}
                password: ${DBT_PASSWORD}
                port: ${DBT_PORT}
                dbname: ${DBT_DBNAME}
                schema: ${DBT_SCHEMA}
                threads: 4
                sslmode: require
          EOF

      - name: Lint SQL with SQLFluff
        run: sqlfluff lint . --dialect postgres

      - name: Install dbt packages
        working-directory: ./fintech_dbt
        run: dbt deps

      - name: Build and test dbt models
        working-directory: ./fintech_dbt
        run: dbt build